export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_CURRENT_EVENT = 'GET_CURRENT_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';

export const GET_CURRENT_REVIEW = 'GET_CURRENT_REVIEW';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const EDIT_REVIEW = 'EDIT_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';

export const GET_ALL_POI = 'GET_ALL_POI';
export const GET_POI_BY_ID = 'GET_POI_BY_ID';

export const GET_EVENTS_ATTENDING = 'GET_EVENTS_ATTENDING';
export const GET_EVENTS_INTERESTED = 'GET_EVENTS_INTERESTED';
