export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_CURRENT_EVENT = 'GET_CURRENT_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';

export const GET_CURRENT_REVIEW = 'GET_CURRENT_REVIEW';
export const CREATE_REVIEW = 'CREATE_REVIEW';
